#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Colorful $TERM (be careful with screen/tmux!)
# (Must before bash-powerline)
if [[ $COLORTERM == gnome-terminal && $TERM != screen* ]]; then
	export TERM=xterm-256color
fi

# My shortcut scripts
source ~/bin/aliases.sh

# Bash powerline
source ~/bin/bash-powerline/bash-powerline.sh
