colorscheme koehler
set guifont=Monospace\ 13
set lines=35 columns=110
set nobackup
set expandtab
set shiftwidth=4
set number

"IMPORTANT! Fix the confliction between preview and MiniBufExpl
let g:miniBufExplBuffersNeeded = 0

autocmd VimEnter * NERDTree

"Force prompt before quit (by :q) under GUI
fun! QuitPrompt()
	let choice = confirm("Really quit VIM?", "&Yes\n&No", 1)
	if choice == 1 | qall | endif
endfun

nnoremap :q<cr> :call QuitPrompt()<cr>
