"set background=dark
colorscheme molokai
set guifont=Monospace\ 13
set lines=35 columns=110
set nobackup
set expandtab
set shiftwidth=4
set number
set winaltkeys=no
set guioptions-=T

let g:bufferline_show_bufnr=1

autocmd VimEnter * NERDTree

"Force prompt before quit (by :q) under GUI
function! QuitPrompt()
	let choice = confirm("Do you really want to quit VIM?", "&Yes\n&No", 1)
	if choice == 1 | qall | endif
endfunction

cnorea <expr> q (getcmdtype() == ':' ? 'call QuitPrompt()' : 'q')
