set undofile
set undodir=$HOME/.vim/undo
"vundle
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Plugin 'gmarik/vundle'

"minibufexpl
Plugin 'fholgado/minibufexpl.vim'
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l
noremap <C-TAB> :MBEbn<CR>
noremap <C-S-TAB> :MBEbp<CR>
cnoremap <expr> bd (getcmdtype() == ':' ? 'MBEbd' : 'bd')
cnoremap <expr> bw (getcmdtype() == ':' ? 'MBEbw' : 'bd')
cnoremap <expr> bun (getcmdtype() == ':' ? 'MBEbun' : 'bd')
let g:miniBufExplShowBufNumbers = 0

"nerdtree
Plugin 'scrooloose/nerdtree'
let NERDTreeMinimalUI=1
let NERDTreeShowBookmarks=1
let NERDTreeWinSize=18
let NERDTreeChDirMode=2
nnoremap <Leader>n :NERDTreeToggle<CR>

"PHP coding
Plugin 'shawncplus/phpcomplete.vim'
Plugin 'php-doc-upgrade'
au FileType php <buffer>
    \ let g:pdv_cfg_Author="Hexcles Ma <bob1211(at)gmail(dot)com>" |
    \ let g:pdv_cfg_Copyright="2014 QSC Tech" |
    \ let g:pdv_cfg_License="Proprietary" |
    \ nnoremap <buffer> <Leader>p :call PhpDocSingle()<CR> |
    \ vnoremap <buffer> <Leader>p :call PhpDocRange()<CR>

"Python coding
Plugin 'hdima/python-syntax'

"YouCompleteMe
Plugin 'Valloric/YouCompleteMe'
let g:ycm_global_ycm_extra_conf='/home/robot/.vim/bundle/YouCompleteMe/ycm_extra_conf_default.py'
let g:ycm_min_num_of_chars_for_completion=3
"let g:ycm_autoclose_preview_window_after_completion=1
"let g:ycm_autoclose_preview_window_after_insertion=1
let g:ycm_key_list_select_completion=['<TAB>']
let g:ycm_key_list_previous_completion=['<S-TAB>']
let g:ycm_key_invoke_completion='<C-k>'
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>
au FileType c,cpp
    \ nnoremap <buffer> <Leader>e :YcmDiags<CR>

"delimitMate
Plugin 'Raimondi/delimitMate'
let delimitMate_expand_cr=1
let delimitMate_expand_space=1
let delimitMate_excluded_regions="Comment,String"
let delimitMate_balance_matchpairs=1

"syntastic
Plugin 'scrooloose/syntastic'
"let g:syntastic_check_on_open=1
let g:syntastic_loc_list_height=5
let g:syntastic_python_checkers=['pyflakes']
nnoremap <Leader>e :Errors<CR>

"vim-markdown
Plugin 'plasticboy/vim-markdown'

"vim-css3-syntax
Plugin 'hail2u/vim-css3-syntax'

"vim-css-color
Plugin 'ap/vim-css-color'

"vim-less
Plugin 'groenewege/vim-less'

"manpageview
Plugin 'dkasak/manpageview'

"vim-python-virtualenv
Plugin 'lambdalisue/vim-python-virtualenv'

"django.vim
"Plugin 'django.vim'

"vim-jade
Plugin 'digitaltoad/vim-jade'

"molokai
Plugin 'tomasr/molokai'

set concealcursor=inv
set conceallevel=2
set previewheight=2
filetype plugin indent on
