"start Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

"--- Overall behaviors ---

"molokai
"A color theme (only used in gvim)
Plugin 'tomasr/molokai'
let g:rehash256 = 1

"vim-twilight
Plugin 'matthewtodd/vim-twilight.git'

"vim-airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline_powerline_fonts = 1
let g:airline#extensions#whitespace#checks = [ 'indent', 'long' ]

"vim-bufferline
Plugin 'bling/vim-bufferline'
let g:bufferline_echo = 0
let g:bufferline_show_bufnr = 0
let g:bufferline_rotate = 1
let g:bufferline_fixed_index = -1

"vim-easymotion (quick move motion support, \\motion)
Plugin 'Lokaltog/vim-easymotion'

"bufkill.vim (Keep window layout when killing buffers)
Plugin 'qpkorr/vim-bufkill'
cnorea <expr> bd (getcmdtype() == ':' ? 'BD' : 'bd')
cnorea <expr> bw (getcmdtype() == ':' ? 'BW' : 'bd')
cnorea <expr> bun (getcmdtype() == ':' ? 'BUN' : 'bd')
noremap <C-TAB> :bn<CR>
noremap <C-S-TAB> :bp<CR>
noremap <Leader>bn :bn<CR>
noremap <Leader>bp :bp<CR>
"exclude quickfix from buffer list
autocmd FileType qf set nobuflisted

"lusty (LustyExplorer + LustyJuggler)
Plugin 'sjbach/lusty'

"nerdtree (file explorer window)
Plugin 'scrooloose/nerdtree'
let NERDTreeMinimalUI = 1
let NERDTreeShowBookmarks = 1
let NERDTreeWinSize = 18
let NERDTreeChDirMode = 2
noremap <Leader>n :NERDTreeToggle<CR>

"delimitMate (match pairs)
Plugin 'Raimondi/delimitMate'
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1
let delimitMate_balance_matchpairs = 1
au FileType python let b:delimitMate_nesting_quotes = ['"', "'"]

"vim-table-mode (toggled by \tm, and then start a line with ||)
Plugin 'dhruvasagar/vim-table-mode'

"vim-commentary (gc)
Plugin 'tpope/vim-commentary'

"ag.vim
Plugin 'rking/ag.vim'

"--- Indent enhancement ---

"indentLine (show indent lines)
Plugin 'Yggdroot/indentLine'

"vim-sleuth (automatically detect buffer indentation: shiftwidth & expandtab)
Plugin 'tpope/vim-sleuth'

"Reset indent line after automatic detection
"A workaround to defer setting this autocmd, so that it's after sleuth.
autocmd VimEnter * autocmd FileType * IndentLinesReset

"Wrapper to manually adjust shiftwidth
command -nargs=1 SW setlocal shiftwidth=<args> | IndentLinesReset

"--- General coding ---

"syntastic
Plugin 'scrooloose/syntastic'
"This must be disabled! Otherwise when openning C/C++ files,
"syntastic will use its own checker to run a check, overwrite YCM.
"let g:syntastic_check_on_open = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_python_checkers = ['flake8']
noremap <Leader>e :SyntasticCheck<CR> :Errors<CR>

"YouCompleteMe
Plugin 'Valloric/YouCompleteMe'
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/ycm_extra_conf_default.py'
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_key_invoke_completion = '<C-k>'
let g:ycm_confirm_extra_conf = 0
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_collect_identifiers_from_tags_files = 1
noremap <Leader>r :YcmForceCompileAndDiagnostics<CR>
noremap <F5> :YcmForceCompileAndDiagnostics<CR>
autocmd FileType c,cpp,objc,objcpp
	\ noremap <buffer> <Leader>e :YcmDiags<CR>
autocmd FileType c,cpp,objc,objcpp,python,cs
	\ noremap <buffer> gD :YcmCompleter GoTo<CR>

"color_coded
Plugin 'jeaye/color_coded'
let g:color_coded_filetypes = ['c', 'cpp', 'objc', 'cuda']
"Highlight settings
"We have to use autocmd, because any colorscheme will run 'hl clear'.
autocmd VimEnter * hi Member ctermfg=170 guifg=#d75fd7 gui=italic
autocmd VimEnter * hi Namespace ctermfg=178 guifg=#d7af00
"Yet links are fine.
hi link Variable Identifier

"tagbar
Plugin 'majutsushi/tagbar'
noremap <Leader>d :TagbarToggle<CR>

"vim-autotag
Plugin 'craigemery/vim-autotag'
"search tags upwards till HOME
set tags+=./tags;$HOME

"lid.vim
Plugin 'yegappan/lid'

"-- PHP --

"phpcomplete.vim (stronger than vim's original one)
Plugin 'shawncplus/phpcomplete.vim'

"php-doc-upgrade (PHPDoc)
Plugin 'php-doc-upgrade'
au FileType php
	\ nnoremap <buffer> <Leader>p :call PhpDocSingle()<CR> |
	\ vnoremap <buffer> <Leader>p :call PhpDocRange()<CR>

"-- Python --

"Highlight unnecessary whitespace and format errors
let python_highlight_all = 1

"vim-python-pep8-indent (make the indent compatible with PEP8)
Plugin 'hynek/vim-python-pep8-indent'

"-- HTML (like) --

"closetag.vim (CTRL+_)
Plugin 'closetag.vim'

"MatchTagAlways (high light tags)
Plugin 'Valloric/MatchTagAlways'

"-- Other languages --

"vim-go
Plugin 'fatih/vim-go'

"vim-markdown (advanced support for Markdown, e.g. navigation)
Plugin 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled = 1

"vim-css3-syntax (full CSS3 support including partial Scss)
Plugin 'hail2u/vim-css3-syntax'

"vim-css-color (show background color for CSS color definitions)
Plugin 'ap/vim-css-color'

"vim-less
Plugin 'groenewege/vim-less'

"vim-stylus
Plugin 'wavded/vim-stylus'

"vim-coffee-script
Plugin 'kchmck/vim-coffee-script'

"manpageview (show man page at cursor, [count]K in normal mode)
Plugin 'dkasak/manpageview'

"django.vim (Django template syntax support)
Plugin 'django.vim'

"vim-jade
Plugin 'digitaltoad/vim-jade'

"llvm.vim
Plugin 'Hexcles/llvm.vim'

"inline_edit
"Automatically switch to other syntax inside embedded code block
"(e.g. JavaScript in HTML and more!)
Plugin 'AndrewRadev/inline_edit.vim'

call vundle#end()
filetype plugin indent on
"end Vundle

"--- Non-plugin settings ---

"enable tag matching for % jump
runtime! macros/matchit.vim

"Use molokai for colorful terminals
"(This has to be after Vundle section ends, otherwise cannot find scheme.)
if &term =~ '.*256color'
	colorscheme molokai
endif

"Fix alt/meta key in GNOME terminal
let c='a'
while c <= 'z'
  exec "set <A-".c.">=\e".c
  exec "imap \e".c." <A-".c.">"
  let c = nr2char(1+char2nr(c))
endw
"Set a very short keycode timeout so that <A-x> will not be confused with <ESC>x
set ttimeout ttimeoutlen=50

"persistent undo
set undofile
set undodir=$HOME/.vim/undo

"preview window
set previewheight=2

"Always show statusline (needed by vim-airline)
set laststatus=2

"Highlight current line
set cursorline

"The first tab completes as much as it can, second tab displays a list of
"options, and the third tab will present a list that allows you to scroll
"through and select filenames beginning with that prefix.
set wildmode=longest,list,full
set wildmenu

"Window navigation and resizing
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l
noremap <A-h> <C-w><
noremap <A-j> <C-W>-
noremap <A-k> <C-W>+
noremap <A-l> <C-w>>

"Quick nohighlight
noremap /<Enter> :nohlsearch<Enter>

"Some uncommon file extensions
autocmd BufRead,BufNewFile *.cuh set filetype=cuda
autocmd BufRead,BufNewFile *.pablo set filetype=python
