#!/bin/sh
# ~/.xprofile

# Setting up language for X
export LANG=zh_CN.UTF-8

# Setting up input method(fcitx)
#export XIM=fcitx
#export XIM_PROGRAM=fcitx
#export XMODIFIERS="@im=fcitx"
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx

# Force wine in 32bit
export WINEARCH=win32

# VDPAU for Intel
export VDPAU_DRIVER=va_gl

# map key
(sleep 5 && xmodmap ~/.Xmodmap &)
